version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: doggy_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: doggy_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
