export const BOT_STATES = {
	START: "START",
	SELECT_SERVICE: "SELECT_SERVICE",
	SELECT_BARBER: "SELECT_BARBER",
	CONFIRM: "CONFIRM",
	SELECT_DATE: "SELECT_DATE",
	SELECT_SLOT: "SELECT_SLOT",
	MAIN_MENU: "MAIN_MENU",
};

export type BotState = keyof typeof BOT_STATES;

